In [25]:
import pandas as pd
import numpy as np

In [26]:
indeed_df = pd.read_csv('indeed_tech.csv')

In [27]:
indeed_df.head()

_id/$oid  \
0  5d99e5238e19238e0431767e   
1  5d99e5258e19238e0431767f   
2  5d99e5258e19238e04317680   
3  5d99e5268e19238e04317681   
4  5d99e5278e19238e04317682   

                                               Titre  \
0  Data Scientist H/F - BIOFORTIS - CDI - Saint-H...   
1                      Data Scientist en Pistage H/F   
2                           Research Scientist (F/M)   
3                      Data scientist (h/f) - Nantes   
4                                 Data Scientist H/F   

                                Entreprise                Ville  \
0  SILLIKER - MERIEUX NUTRISCIENCES FRANCE  Saint-Herblain (44)   
1                           Page Personnel          Nantes (44)   
2                   Institut Laue-Langevin               France   
3                         Maisons du Monde          Vertou (44)   
4                                    KANDY     Treillières (44)   

                      Salaire  Type_de_contrat  \
0             40 000 € par an              NaN   
1                        None              NaN   
2                        None              NaN   
3                        None              NaN   
4  30 000 € - 40 000 € par an              NaN   

                                 Descriptif_du_poste     Date_de_publication  \
0  #JobAlert #Stats #DataScientist #Nantes #Mérie...        il y a 30+ jours   
1  Data Scientist en Pistage H/F. Études et prosp...  ouestfrance-emploi.com   
2  We receive over 2000 visiting scientists per y...      brightrecruits.com   
3  Vous collaborez étroitement avec les Data Scie...          il y a 3 jours   
4  KANDY propose un poste de Data Scientist au se...         il y a 27 jours   

     Scrapped_job Scrapped_location Type de contrat Descriptif du poste  \
0  data scientist            Nantes             NaN                 NaN   
1  data scientist            Nantes             NaN                 NaN   
2  data scientist            Nantes             NaN                 NaN   
3  data scientist            Nantes             NaN                 NaN   
4  data scientist            Nantes             NaN                 NaN   

  Date de publication  
0                 NaN  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN

In [28]:
indeed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12432 entries, 0 to 12431
Data columns (total 13 columns):
_id/$oid               12432 non-null object
Titre                  12432 non-null object
Entreprise             12430 non-null object
Ville                  12430 non-null object
Salaire                12431 non-null object
Type_de_contrat        0 non-null float64
Descriptif_du_poste    12428 non-null object
Date_de_publication    12411 non-null object
Scrapped_job           12431 non-null object
Scrapped_location      12431 non-null object
Type de contrat        1 non-null object
Descriptif du poste    1 non-null object
Date de publication    1 non-null object
dtypes: float64(1), object(12)
memory usage: 1.2+ MB


In [29]:
indeed_df['Salaire'].value_counts()

None                          10353
35 000 € - 45 000 € par an      111
30 000 € - 40 000 € par an       90
40 000 € - 50 000 € par an       74
50 000 € par an                  68
40 000 € par an                  56
35 000 € - 40 000 € par an       56
45 000 € par an                  55
40 000 € - 45 000 € par an       54
45 000 € - 55 000 € par an       51
55 000 € par an                  43
30 000 € - 35 000 € par an       41
40 000 € - 55 000 € par an       32
40 000 € - 60 000 € par an       30
45 000 € - 50 000 € par an       29
45 000 € - 60 000 € par an       25
60 000 € par an                  25
30 000 € - 50 000 € par an       23
35 000 € - 50 000 € par an       21
30 000 € - 45 000 € par an       18
35 000 € par an                  18
300 € - 500 € par jour           18
38 000 € - 42 000 € par an       17
50 000 € - 65 000 € par an       17
42 000 € par an                  16
34 000 € - 38 000 € par an       16
65 000 € par an                  15
50 000 € - 55 000 € par an  

In [30]:
indeed_df['Scrapped_job'].value_counts()

développeur              7774
data scientist           1760
business intelligence    1675
data analyst             1222
Name: Scrapped_job, dtype: int64

In [31]:
salary = indeed_df['Salaire'][579]

In [32]:
salary

'None'

# Créer une fonction pour parser les salaires

In [33]:
#for i in salary:
    #print(i)

In [34]:
### def parse_salary():
    #### Il y a des salaires par année, par mois, par heure
    #### Salaire non indiqués aussi
    #### Donc 3 conditions différentes à créer

In [35]:
#if type(salary) == str:
    #print("ok")

#                                 ----> Penser aux regex ! <------

# Test des regex sur une ligne du dataset qui contient une fourchette de salaire

In [36]:
import re
salary

'None'

In [37]:
sal = salary.replace(' ', '')
sal

'None'

In [38]:
#salary.split('(\d+)')

In [39]:
#split_salary = salary.split("-")

In [40]:
#if '-' in sal:
    #salary_2 = salary.replace('€', '')
    #print(salary_2)
    
    #x = re.findall('\d+', sal)

In [41]:
#x

# ---> Fonction qui récupère les salaires selon les cas (an,mois...)

# 1) Parser et voir les cas : "Par an", "Par mois", "Par heure"

In [42]:
# On teste les différents cas pour le salaire (an,mois,semaine,jour,heure)

salary = '55 € par heure'
salary

'55 € par heure'

In [43]:
def parse_salary(salary):
    
    # Supprime les espaces dans les valeurs de salaires
    
    sal = salary.replace(' ', '')
    
    # PENSER AU NAN
    
    ### if salary == nan
    
    ########### On parse si le salaire est "par an"
    
    if 'par an' in salary:
        if '-' in salary:
            x = re.findall('\d+', sal)
            avg = (int(x[0]) + int(x[1]))/(len(x))
            return avg
        else:
            x = re.findall('\d+', sal)
            return int(x[0])
        
    ########## Sinon on parse si le salaire est "par mois"
    
    elif 'par mois' in salary:
        if '-' in salary:
            x = re.findall('\d+', sal)
            avg = (int(x[0]) + int(x[1]))/(len(x))
            return (avg * 12) 
        else:
            x = re.findall('\d+', sal)
            return (int(x[0]) * 12)
    
    ########## Sinon on parse si le salaire est "par semaine"
    
    elif 'par semaine' in salary:
        if '-' in salary:
            x = re.findall('\d+', sal)
            avg = (int(x[0]) + int(x[1]))/(len(x))
            return (avg * 4 * 12) 
        else:
            x = re.findall('\d+', sal)
            return (int(x[0]) * 4 * 12)
    
    
    ########## Sinon on parse si le salaire est "par jour"
    
    elif 'par jour' in salary:
        if '-' in salary:
            x = re.findall('\d+', sal)
            avg = (int(x[0]) + int(x[1]))/(len(x))
            return (avg * 20 * 12)
        else:
            x = re.findall('\d+', sal)
            return (int(x[0]) * 20 * 12)
    
    ########## Sinon on parse si le salaire est "heure"
    
    elif 'par heure' in salary:
        if '-' in salary:
            x = re.findall('\d+', sal)
            avg = (int(x[0]) + int(x[1]))/(len(x))
            return (avg * 35 * 4 * 12)
        else:
            x = re.findall('\d+', sal)
            return (int(x[0]) * 35 * 4 * 12)
    
    

In [44]:
parse_salary(salary)

92400

In [45]:
y = indeed_df['Salaire']
len(y)

12432

In [46]:
salaires = np.array(indeed_df['Salaire'])
salaires

array(['40 000 € par an', 'None', 'None', ..., 'None', 'None', 'salary'],
      dtype=object)

In [47]:
len(salaires)

12432

In [48]:
sala = []
for salary in salaires:
    #print(salary)
    s = parse_salary(salary)
    print(s)
    sala.append(s)
    #sal.append(salaires[salary])

40000
None
None
None
35000.0
40000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
37500.0
None
None
20160
None
None
None
44000
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
39000.0
None
None
40000.0
None
None
None
None
40000
None
None
37500.0
None
None
42500.0
47500.0
45000.0
None
27000
25000.0
33750.0
None
None
None
None
None
None
None
None
33000
20760
None
45000.0
None
38500.0
45000.0
35000
38500.0
39000.0
None
40000
None
None
None
None
None
None
None
39000.0
None
None
40000.0
None
None
None
38000
39000.0
None
None
None
None
None
None
37500.0
35000.0
None
None
None
40000
None
None
None
37500.0
None
None
None
40000
None
30000
None
None
None
None
None
None
None
None
None
45000.0
None
30000.0
40000.0
39500.0
None
38000
45000
35000.0
None
None
None
None
None
None
None
27000.0
None
40000
None
45000
None
None
42000
None
28000
None
None
None
42

None
None
None
36500.0
30000.0
None
None
None
None
60000.0
None
50500.0
40000.0
None
35000.0
None
None
None
None
None
None
40000.0
None
None
None
None
None
None
None
37500.0
None
None
31000.0
None
None
None
None
None
None
None
None
None
None
None
27500.0
None
None
None
42500.0
27500.0
None
None
37500.0
None
None
None
None
14004.0
None
None
None
None
None
None
None
None
45000.0
None
None
42500.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
8700.0
32500.0
35000.0
None
None
None
None
None
53000
None
34000.0
47500.0
None
None
None
None
None
None
None
None
37500.0
None
None
60000.0
None
None
None
None
None
41000.0
37000.0
None
36000.0
None
None
24000.0
None
37500.0
None
40000.0
None
None
None
None
36000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
35000.0
None
None
None
47500.0
None
24000
None
22500.0
None
35000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
23

None
None
None
None
None
41000.0
None
None
None
None
39000.0
None
None
29000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
30000.0
36600.0
None
None
None
None
None
None
None
None
None
None
None
None
45000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
36000.0
None
None
None
None
70000.0
70000.0
None
None
55000.0
None
None
None
None
None
36000.0
None
None
None
None
21250.0
None
40000.0
38500.0
None
None
None
None
None
None
None
None
None
None
None
None
35000.0
40000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
35000.0
None
34200.0
37500.0
None
None
35000.0
None
None
None
35000
None
None
None
45000.0
31500.0
None
None
None
None
None
35000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
50000.0
50000.0
None
50000.0
None
None
47500.0
None
None
42500.0
None
None
None
None
None
None
None
50000.0
37500.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
75000.0
50000.0
None
None
None
None
52500.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
7200
None
60000.0
None
None
None
60000.0
None
None
65000
None
None
None
None
None
None
None
None
None
53500.0
None
None
None
None
None
None
None
45000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
13440
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
58000
47500.0
None
None
52500.0
None
None
None
None
None
None
None
None
None
None
None
55000
None
None
None
None
None
None
Non

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
13800.0
None
None
None
None
None
None
None
None
None
None
None
None
50000
55000.0
None
None
None
None
None
None
12000.0
None
None
None
None
None
None
None
42500.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
50000
90000
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
37000.0
None
37000.0
None
None
None
None
None
None
None
None
None
None
9600.0
25200.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
50000
None
None
None
None
None
None
None
None
65000.0
None
None
None
None
None
None
None
44500.0
None
None
None
None
60000
None
None
None
None
None
None
None
None
None
42500.0
45000.0
None
None
None
None
None
None
None
None
40000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
45000
None
None
None
None
45000
None
None
None
None
None
None
None
None
None
None
40000.0
40000.0
None
None
None

AttributeError: 'float' object has no attribute 'replace'

In [49]:
len(sala)

9582

In [50]:
sala[0:5]

[40000, None, None, None, 35000.0]

In [51]:
#indeed_df['NEW SALARY'] = sala

In [52]:
indeed_df['Salaire'][9582]

nan

In [53]:
# bill_df = bill_df.dropna(subset=['num_guests'])
indeed_df = indeed_df.dropna(subset=['Salaire'])

In [54]:
salaires_2 = np.array(indeed_df['Salaire'])

In [55]:
indeed_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12431 entries, 0 to 12431
Data columns (total 13 columns):
_id/$oid               12431 non-null object
Titre                  12431 non-null object
Entreprise             12430 non-null object
Ville                  12430 non-null object
Salaire                12431 non-null object
Type_de_contrat        0 non-null float64
Descriptif_du_poste    12428 non-null object
Date_de_publication    12410 non-null object
Scrapped_job           12430 non-null object
Scrapped_location      12430 non-null object
Type de contrat        1 non-null object
Descriptif du poste    1 non-null object
Date de publication    1 non-null object
dtypes: float64(1), object(12)
memory usage: 1.3+ MB


In [56]:
sala_2 = []
for salary in salaires_2:
    #print(salary)
    s = parse_salary(salary)
    print(s)
    sala_2.append(s)
    #sal.append(salaires[salary])

40000
None
None
None
35000.0
40000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
37500.0
None
None
20160
None
None
None
44000
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
39000.0
None
None
40000.0
None
None
None
None
40000
None
None
37500.0
None
None
42500.0
47500.0
45000.0
None
27000
25000.0
33750.0
None
None
None
None
None
None
None
None
33000
20760
None
45000.0
None
38500.0
45000.0
35000
38500.0
39000.0
None
40000
None
None
None
None
None
None
None
39000.0
None
None
40000.0
None
None
None
38000
39000.0
None
None
None
None
None
None
37500.0
35000.0
None
None
None
40000
None
None
None
37500.0
None
None
None
40000
None
30000
None
None
None
None
None
None
None
None
None
45000.0
None
30000.0
40000.0
39500.0
None
38000
45000
35000.0
None
None
None
None
None
None
None
27000.0
None
40000
None
45000
None
None
42000
None
28000
None
None
None
42

25000.0
None
None
None
35000.0
None
None
46200.0
None
None
32500.0
None
None
None
None
None
None
None
None
None
None
33000.0
36500.0
None
None
None
35000.0
None
None
None
None
None
None
31500.0
35000.0
None
35000
32500.0
None
None
32500.0
40000.0
None
None
35000.0
None
33000.0
42500.0
38000
32000
None
38500.0
40000.0
45000.0
42500.0
None
35000.0
None
None
None
37500.0
None
47500.0
None
None
42500.0
42500.0
47500.0
None
None
None
None
None
72000
None
None
None
None
None
None
None
None
None
45000
None
None
None
None
None
None
None
None
None
27500.0
None
None
None
None
35000
None
25000
None
37000.0
None
None
None
None
28500.0
None
35000.0
96000.0
69600
96000.0
96000.0
None
None
40000.0
28000.0
35500.0
None
36000.0
40000
None
None
None
None
45000
None
None
None
None
None
None
28500.0
None
None
None
None
36500.0
30000.0
None
None
None
None
60000.0
None
50500.0
40000.0
None
35000.0
None
None
None
None
None
None
40000.0
None
None
None
None
None
None
None
37500.0
None
None
31000.0
None
None
No

35000.0
None
None
None
35000
None
None
None
45000.0
31500.0
None
None
None
None
None
35000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
39000.0
None
None
None
None
None
None
None
None
None
36000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
37500.0
None
None
None
None
None
35000.0
36000
None
None
None
None
None
None
None
None
None
None
40000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
35000.0
38000
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
36000.0
None
None
36000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
40000.0
35000.0
None
None
None
None
None
None
None
None
None
None
57500.0
None
None
None
None
None
None
None
None
None
38500.0
None
None
None
None
None

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
13200
None
None
None
None
None
None
None
None
None
None
52800.0
None
None
None
None
None
None
None
None
None
None
None
40000.0
None
None
None
None
None
30500.0
50000
None
None
None
None
None
None
None
None
None
38500.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
50000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
20400
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
70000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
96000
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
47500.0
None
None
None
None
None
None
None
None
None
None
37500.0
None
42500.0
None

None
None
None
51500.0
65000.0
None
None
None
None
None
None
None
None
None
45000.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
57500.0
None
None
None
55000
None
33000.0
46500.0
46500.0
None
32500.0
None
55000
None
45000.0
40000
30000.0
36000
None
None
None
None
8400
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
42500.0
None
None
None
45000.0
41500.0
40000.0
41500.0
32500.0
55000
31584
None
None
None
None
None
None
None
None
None
None
None
None
40000.0
None
10200
None
None
32000
None
30000
6720
None
6612
6936
None
35000
None
None
35000
None
None
None
27500.0
None
None
None
None
None
None
None
None
29500.0
None
55000
None
None
None
None
None
None
None
32500.0
37500.0
None
None
None
35000
38000
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
43000
None
No

In [57]:
len(sala_2)

12431

In [58]:
indeed_df['NEW SALARY'] = sala_2

In [59]:
indeed_df['NEW SALARY']

0        40000.0
1            NaN
2            NaN
3            NaN
4        35000.0
5        40000.0
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28           NaN
29           NaN
          ...   
12402        NaN
12403        NaN
12404        NaN
12405     6612.0
12406        NaN
12407        NaN
12408        NaN
12409     8400.0
12410        NaN
12411        NaN
12412        NaN
12413        NaN
12414        NaN
12415        NaN
12416        NaN
12417        NaN
12418        NaN
12419        NaN
12420        NaN
12421        NaN
12422     6612.0
12423        NaN
12424    35000.0
12425        NaN
12426        NaN
12427        NaN
12428        NaN
12429        N

In [60]:
indeed_df

_id/$oid  \
0      5d99e5238e19238e0431767e   
1      5d99e5258e19238e0431767f   
2      5d99e5258e19238e04317680   
3      5d99e5268e19238e04317681   
4      5d99e5278e19238e04317682   
5      5d99e5288e19238e04317683   
6      5d99e5288e19238e04317684   
7      5d99e5298e19238e04317685   
8      5d99e52a8e19238e04317686   
9      5d99e52b8e19238e04317687   
10     5d99e52c8e19238e04317688   
11     5d99e52c8e19238e04317689   
12     5d99e52d8e19238e0431768a   
13     5d99e52d8e19238e0431768b   
14     5d99e5338e19238e0431768c   
15     5d99e5348e19238e0431768d   
16     5d99e5348e19238e0431768e   
17     5d99e5358e19238e0431768f   
18     5d99e5358e19238e04317690   
19     5d99e5368e19238e04317691   
20     5d99e5378e19238e04317692   
21     5d99e5388e19238e04317693   
22     5d99e5398e19238e04317694   
23     5d99e54a8e19238e04317695   
24     5d99e54b8e19238e04317696   
25     5d99e54b8e19238e04317697   
26     5d99e54c8e19238e04317698   
27     5d99e54d8e19238e04317699   
28     5d99e54d8e19238e0431769a   
29     5d99e54e8e19238e0431769b   
...                         ...   
12402  5d9a79e28e19238e0431a6fa   
12403  5d9a79e38e19238e0431a6fb   
12404  5d9a79e38e19238e0431a6fc   
12405  5d9a79e48e19238e0431a6fd   
12406  5d9a79e58e19238e0431a6fe   
12407  5d9a79e58e19238e0431a6ff   
12408  5d9a79e68e19238e0431a700   
12409  5d9a79ea8e19238e0431a701   
12410  5d9a79eb8e19238e0431a702   
12411  5d9a79eb8e19238e0431a703   
12412  5d9a79ec8e19238e0431a704   
12413  5d9a79ed8e19238e0431a705   
12414  5d9a79ed8e19238e0431a706   
12415  5d9a79ef8e19238e0431a707   
12416  5d9a79ef8e19238e0431a708   
12417  5d9a79f08e19238e0431a709   
12418  5d9a79f48e19238e0431a70a   
12419  5d9a79f58e19238e0431a70b   
12420  5d9a79f68e19238e0431a70c   
12421  5d9a79f78e19238e0431a70d   
12422  5d9a79f88e19238e0431a70e   
12423  5d9a79f88e19238e0431a70f   
12424  5d9a79f98e19238e0431a710   
12425  5d9a79fa8e19238e0431a711   
12426  5d9a79ff8e19238e0431a712   
12427  5d9a7a008e19238e0431a713   
12428  5d9a7a008e19238e0431a714   
12429  5d9a7a018e19238e0431a715   
12430  5d9a7a028e19238e0431a716   
12431  5d9ae538fe533a6618915072   

                                                   Titre  \
0      Data Scientist H/F - BIOFORTIS - CDI - Saint-H...   
1                          Data Scientist en Pistage H/F   
2                               Research Scientist (F/M)   
3                          Data scientist (h/f) - Nantes   
4                                     Data Scientist H/F   
5                           Ingénieur Data Scientist H/F   
6                          Data Scientist en Pistage H/F   
7                       DATA SCIENTIST JUNIOR H/F NANTES   
8      Expert IA - Data Scientist / Data analyst / Fr...   
9      Data Scientist en Pistage H/F - Naval Group, l...   
10                                 Consultant Data (h/f)   
11                             Data Engineer / Freelance   
12                               Ingénieur R&D NLP - F/H   
13     Senior Backend Developer (f/m/x) (relocated to...   
14     Un développeur python spark + Git sur Nantes /...   
15                           Ingénieur de production F/H   
16                            Senior Data Engineer (M/F)   
17                    CONSULTANT DATA SCIENCE H/F RENNES   
18                           Développeur Java/Apex (H/F)   
19                                   Architecte Data H/F   
20         Développeur confirmé / Référent technique F/H   
21      Consultant Innovation ( data, IA, …)_ Nantes H/F   
22     Ingénieur Junior Developpement Software (Reloc...   
23                            DATA analyste informatique   
24                                          DATA ANALYST   
25                                      Data Analyst H/F   
26                         Data scientist (h/f) - Nantes   
27                                      Data Analyst H/F   
28                                 Security Data Analyst   
29                                      Data Analyst

In [61]:
future_df = indeed_df.copy()

In [62]:
future_df.shape

(12431, 14)

In [63]:
#bill_df = bill_df.dropna(subset=['num_guests'])

future_df = future_df.dropna(subset=['NEW SALARY'])

In [64]:
future_df.shape

(2077, 14)

# ---> Il y a 2077 offres avec des salaires.

In [65]:
future_df['NEW SALARY'].shape

(2077,)

In [66]:
#future_df['NEW SALARY']

In [67]:
# Prédire le salaire selon le nombre de skills
# Prédire le salaire selon l'expérience
# La ville

In [68]:
future_df['NEW SALARY']

0        40000.0
4        35000.0
5        40000.0
35       37500.0
38       20160.0
42       44000.0
62       39000.0
65       40000.0
70       40000.0
73       37500.0
76       42500.0
77       47500.0
78       45000.0
80       27000.0
81       25000.0
82       33750.0
91       33000.0
92       20760.0
94       45000.0
96       38500.0
97       45000.0
98       35000.0
99       38500.0
100      39000.0
102      40000.0
110      39000.0
113      40000.0
117      38000.0
118      39000.0
125      37500.0
          ...   
12235    23500.0
12242    44000.0
12251    38500.0
12252    23500.0
12253    45000.0
12255    42500.0
12257    84000.0
12261    45000.0
12262     6000.0
12267    55000.0
12277    31200.0
12279    50000.0
12282    38500.0
12285    31200.0
12287    55000.0
12290    45000.0
12294    30000.0
12302    37500.0
12314    31000.0
12317    36000.0
12337    41000.0
12338    36500.0
12351    62500.0
12358     6600.0
12390    62500.0
12400    35000.0
12405     6612.0
12409     8400

In [70]:
future_df.head()

_id/$oid  \
0   5d99e5238e19238e0431767e   
4   5d99e5278e19238e04317682   
5   5d99e5288e19238e04317683   
35  5d99e5578e19238e043176a1   
38  5d99e55a8e19238e043176a4   

                                                Titre  \
0   Data Scientist H/F - BIOFORTIS - CDI - Saint-H...   
4                                  Data Scientist H/F   
5                        Ingénieur Data Scientist H/F   
35  Ingénieur de production / Analyste d’exploitat...   
38   Data Analyst confirmé (H/F) - Nantes / Freelance   

                                 Entreprise                Ville  \
0   SILLIKER - MERIEUX NUTRISCIENCES FRANCE  Saint-Herblain (44)   
4                                     KANDY     Treillières (44)   
5                             EPSILON-ALCEN          Nantes (44)   
35                                Synchrone               France   
38                          INFOTEL CONSEIL          Nantes (44)   

                       Salaire  Type_de_contrat  \
0              40 000 € par an              NaN   
4   30 000 € - 40 000 € par an              NaN   
5   30 000 € - 50 000 € par an              NaN   
35  30 000 € - 45 000 € par an              NaN   
38           420 € par semaine              NaN   

                                  Descriptif_du_poste Date_de_publication  \
0   #JobAlert #Stats #DataScientist #Nantes #Mérie...    il y a 30+ jours   
4   KANDY propose un poste de Data Scientist au se...     il y a 27 jours   
5   Ingénieur data scientist ou similaire: Partici...     il y a 23 jours   
35  Ingénieur de production / analyste d’exploitat...     il y a 26 jours   
38  Nous recherchons pour l’un de nos clients Nant...      Freelance-info   

      Scrapped_job Scrapped_location Type de contrat Descriptif du poste  \
0   data scientist            Nantes             NaN                 NaN   
4   data scientist            Nantes             NaN                 NaN   
5   data scientist            Nantes             NaN                 NaN   
35    data analyst            Nantes             NaN                 NaN   
38    data analyst            Nantes             NaN                 NaN   

   Date de publication  NEW SALARY  
0                  NaN     40000.0  
4                  NaN     35000.0  
5                  NaN     40000.0  
35                 NaN     37500.0  
38                 NaN     20160.0

In [75]:
future_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2077 entries, 0 to 12424
Data columns (total 14 columns):
_id/$oid               2077 non-null object
Titre                  2077 non-null object
Entreprise             2077 non-null object
Ville                  2077 non-null object
Salaire                2077 non-null object
Type_de_contrat        0 non-null float64
Descriptif_du_poste    2077 non-null object
Date_de_publication    2073 non-null object
Scrapped_job           2077 non-null object
Scrapped_location      2077 non-null object
Type de contrat        0 non-null object
Descriptif du poste    0 non-null object
Date de publication    0 non-null object
NEW SALARY             2077 non-null float64
dtypes: float64(2), object(12)
memory usage: 323.4+ KB


# WORD EMBEDDING

In [90]:
# word2vec

In [91]:
sentences = future_df['Descriptif_du_poste']

In [93]:
from gensim.test.utils import common_texts, get_tmpfile
from gensim.models import Word2Vec

In [94]:
model = Word2Vec(sentences, size = 250, alpha = 0.025, min_alpha = 0.00025, min_count = 5, window = 3, sg = 1)
model.train(sentences, total_examples = len(sentences), epochs = 80)

(6462762, 25319440)

In [98]:
from sklearn.feature_extraction.text import CountVectorizer

In [99]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]

In [101]:
vectorizer = CountVectorizer()

In [102]:
X = vectorizer.fit_transform(corpus)

In [103]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [104]:
print(X.toarray())  

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [105]:
y = vectorizer.fit_transform(sentences)

In [108]:
#print(vectorizer.get_feature_names())

In [107]:
print(y.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
